import { create } from "zustand";

/**
 * Global visualization store.
 * Manages playback state, speed, and current step across all algorithm views.
 */
export const useVisualizationStore = create((set, get) => ({
  // Playback
  isPlaying: false,
  speed: 500, // ms between steps
  currentStep: 0,
  totalSteps: 0,

  // Data
  inputData: [],
  steps: [], // Array of snapshot objects generated by algorithm

  // Rendering mode (for comparison purposes)
  renderMode: "svg", // "svg" | "canvas"

  // Actions
  play: () => set({ isPlaying: true }),
  pause: () => set({ isPlaying: false }),
  togglePlay: () => {
    const { isPlaying, currentStep, totalSteps } = get();
    if (!isPlaying && currentStep >= totalSteps - 1) return; // don't play if at end
    set({ isPlaying: !isPlaying });
  },
  reset: () => set({ isPlaying: false, currentStep: 0 }),
  setSpeed: (speed) => set({ speed }),
  setRenderMode: (mode) => set({ renderMode: mode }),

  stepForward: () => {
    const { currentStep, totalSteps } = get();
    if (currentStep < totalSteps - 1) {
      set({ currentStep: currentStep + 1 });
    } else {
      set({ isPlaying: false });
    }
  },

  stepBackward: () => {
    const { currentStep } = get();
    if (currentStep > 0) {
      set({ currentStep: currentStep - 1 });
    }
  },

  goToStep: (step) => set({ currentStep: step }),

  loadAlgorithm: (inputData, steps) =>
    set({
      inputData,
      steps,
      totalSteps: steps.length,
      currentStep: 0,
      isPlaying: false,
    }),
}));